---

- name: ansible-users | manage systemusers {{ user.name }}
  user:
    name: "{{ user.name }}"
    state: "{{ user.state | default('present') }}"
    create_home: "{{ user.create_home | default(system_user_default_create_home)}}"
    home: "{{ user.home | default(system_user_default_home)}}"
    shell: /sbin/nologin
    comment: "{{ user.comment | default(omit) }}"
    uid: "{{ user.uid | default(omit) }}"
    group: "{{ user.group | default(omit) }}"
    groups: "{{ user.groups | default(omit) }}"
    system: yes